name: Hello World!

on:
  push:
    branches:
      - rtjil-de

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Show current time
        run: |
          echo "$(date)"
      - name: Show current dir
        run: |
          echo "$(ls)"
