name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

env:
  CONDITION: ${{ github.event.commits && contains(join(github.event.commits.*.message, ', '), '#skip') }}

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - name: Show Github Context
        run: |
          echo "Event: ${{ github.event_name }}"

  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      - run: npm run eslint
      - run: npm run build
      - run: npm run test
      - run: exit 1

  discord_notify:
    needs: [simple_deployment_pipeline]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Debug webhook
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
           echo "❌ Secret is empty or not passed"
          else
           echo "✅ Secret exists (not showing for security)"
          fi

      - name: Discord Success Notification
        if: ${{ needs.simple_deployment_pipeline.result == 'success' }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: Deploy status
          avatarUrl: https://pzayzfkambqnvlzxqlbb.supabase.co/storage/v1/object/public/messenger-sm/butlet_bot%20(1).jpg
          text: ✅Deploy succeed
          severity: info
          color: '#00ff84'
          title: Built and ready
          description: |
            📦 Repo: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})
            👤 Actor: ${{ github.actor }}
            🔀 Branch: ${{ github.ref }}
            🔗 Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Discord Failure Notification
        if: ${{ needs.simple_deployment_pipeline.result == 'failure' }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: Deploy status
          avatarUrl: https://pzayzfkambqnvlzxqlbb.supabase.co/storage/v1/object/public/messenger-sm/butlet_bot.png
          text: |
            ⛔ Deployment failed!
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Commit URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}
            Author: ${{ github.actor }}
            Workflow: ${{ github.workflow }}
            Job: ${{ github.job }}
            Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          severity: error
          color: '#ff3c00'
          title: Build failed

  playwright_tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [simple_deployment_pipeline]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10

  render_deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [simple_deployment_pipeline, playwright_tests]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        if: ${{ env.CONDITION == 'false'  }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -v "$deploy_url"

  tag_release:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [render_deploy]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.CONDITION == 'false'  }}
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        with:
          initial_version: 0.0.0
          fetch-depth: '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
